name: qa4sm-reader
channels:
  - defaults
  - conda-forge
dependencies:
  - xarray>=2024.0.0
  - netcdf4
  - gdal
  - hdf5
  - libtiff<=4.5.1
  - pip
  - python
  - pyproj
  - rasterio
  - rioxarray
  - proj
  - qtbase<=6.7.2
  - pip:
      - cartopy>=0.23.0
      - cftime>=1.6.4
      - colorcet
      - h5netcdf>=1.4.1
      - matplotlib
      - netcdf4
      - numpy
      - parse
      - pandas
      - pygeogrids
      - pyqt5
      - pytesmo
      - pytest
      - pytest-cov
      - rio-tiler
      - scikit-learn
      - scipy
      - seaborn
      - shapely
      - xarray>=2024.0.0
      - yapf